# coding: utf-8

"""
    v10 - Shared API

    The bol.com API shared logic.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bol_shared_api_client.api.process_status_api import ProcessStatusApi


class TestProcessStatusApi(unittest.TestCase):
    """ProcessStatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProcessStatusApi()

    def tearDown(self) -> None:
        pass

    def test_get_process_status(self) -> None:
        """Test case for get_process_status

        Get the status of an asynchronous process by process status id
        """
        pass

    def test_get_process_status_bulk(self) -> None:
        """Test case for get_process_status_bulk

        Get the status of multiple asynchronous processes by an array of process status ids for a retailer
        """
        pass

    def test_get_process_status_entity_id(self) -> None:
        """Test case for get_process_status_entity_id

        Get the status of an asynchronous process by entity id and event type for a retailer
        """
        pass


if __name__ == '__main__':
    unittest.main()
