# coding: utf-8

# flake8: noqa
"""
    v10 - Shared API

    The bol.com API shared logic.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from bol_shared_api_client.models.bulk_process_status_request import BulkProcessStatusRequest
from bol_shared_api_client.models.link import Link
from bol_shared_api_client.models.problem import Problem
from bol_shared_api_client.models.process_status import ProcessStatus
from bol_shared_api_client.models.process_status_id import ProcessStatusId
from bol_shared_api_client.models.process_status_response import ProcessStatusResponse
from bol_shared_api_client.models.violation import Violation
